package module

import (
    "fmt"
    "os"
    "path/filepath"
)

// Config controls where module files are written.
type Config struct {
    OutputDir string
}

// Generate writes Terraform module folders and files to disk.
func Generate(mods []Module, cfg Config) error {
    if cfg.OutputDir == "" {
        return fmt.Errorf("output directory is required")
    }

    // Ensure the root output directory exists.
    if err := os.MkdirAll(cfg.OutputDir, 0o755); err != nil {
        return fmt.Errorf("failed to create module output dir: %w", err)
    }

    for _, mod := range mods {
        modDir := filepath.Join(cfg.OutputDir, mod.Name)

        // Create the module directory.
        if err := os.MkdirAll(modDir, 0o755); err != nil {
            return fmt.Errorf("failed to create module dir %s: %w", modDir, err)
        }

        // Write a minimal main.tf file.
        mainPath := filepath.Join(modDir, "main.tf")
        f, err := os.Create(mainPath)
        if err != nil {
            return fmt.Errorf("failed to create %s: %w", mainPath, err)
        }

        // Minimal placeholder Terraform module.
        fmt.Fprintf(f, "# Terraform module for %s\n", mod.Name)
        fmt.Fprintf(f, "# Generated by Terraforge\n\n")

        // Placeholder resource block.
        fmt.Fprintf(f, "resource \"%s\" \"%s\" {}\n", mod.Name, mod.Name)

        f.Close()
    }

    return nil
}