package providersrc

import (
	"bytes"
	"fmt"
	"path/filepath"

	"github.com/amiasea/packages/terraforge-cli/internal/codegen/modulegraph"
	"github.com/amiasea/packages/terraforge-cli/internal/filesystem"
)

// Config controls where provider source files are written.
type Config struct {
	OutputDir string
	Package   string
}

// GenerateFromGraphInternal emits provider source code based on the module graph.
func GenerateFromGraph(fs *filesystem.FS, g *modulegraph.Graph, cfg Config) error {
	if cfg.OutputDir == "" {
		return fmt.Errorf("output directory is required")
	}
	if cfg.Package == "" {
		return fmt.Errorf("package name is required")
	}

	// Ensure provider output directory exists.
	if err := fs.WriteFile(filepath.Join(cfg.OutputDir, ".keep"), []byte{}); err != nil {
		return fmt.Errorf("failed to initialize provider output directory: %w", err)
	}

	// Path to the generated provider file.
	providerPath := filepath.Join(cfg.OutputDir, "provider.go")

	// Build provider.go content in memory.
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by Terraforge. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", cfg.Package)

	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "    \"context\"\n")
	fmt.Fprintf(&buf, "    \"github.com/hashicorp/terraform-plugin-framework/provider\"\n")
	fmt.Fprintf(&buf, ")\n\n")

	fmt.Fprintf(&buf, "// Provider returns a Terraform provider implementation.\n")
	fmt.Fprintf(&buf, "func Provider() provider.Provider {\n")
	fmt.Fprintf(&buf, "    return &terraforgeProvider{}\n")
	fmt.Fprintf(&buf, "}\n\n")

	fmt.Fprintf(&buf, "type terraforgeProvider struct{}\n\n")

	fmt.Fprintf(&buf, "func (p *terraforgeProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {\n")
	fmt.Fprintf(&buf, "    resp.TypeName = \"terraforge\"\n")
	fmt.Fprintf(&buf, "}\n")

	// Write provider.go using the filesystem abstraction.
	if err := fs.WriteFile(providerPath, buf.Bytes()); err != nil {
		return fmt.Errorf("failed to write provider source file %s: %w", providerPath, err)
	}

	return nil
}
