package module

import (
	"fmt"
	"os"
	"path/filepath"
)

// Config controls where module files are written.
type Config struct {
	OutputDir string
}

// Generate writes Terraform module folders and files to disk.
func Generate(mods []Module, cfg Config) error {
	if cfg.OutputDir == "" {
		return fmt.Errorf("output directory is required")
	}

	// Ensure the root output directory exists.
	if err := os.MkdirAll(cfg.OutputDir, 0o755); err != nil {
		return fmt.Errorf("failed to create module output dir: %w", err)
	}

	// Generate one Terraform module per resource.
	for _, mod := range mods {
		modDir := filepath.Join(cfg.OutputDir, mod.Name)

		if err := os.MkdirAll(modDir, 0o755); err != nil {
			return fmt.Errorf("failed to create module dir %s: %w", modDir, err)
		}

		mainPath := filepath.Join(modDir, "main.tf")
		f, err := os.Create(mainPath)
		if err != nil {
			return fmt.Errorf("failed to create %s: %w", mainPath, err)
		}

		// Basic Terraform module stub
		fmt.Fprintf(f, "# Terraform module for %s\n", mod.Name)
		fmt.Fprintf(f, "# Generated by Terraforge\n\n")

		fmt.Fprintf(f, "resource \"%s\" \"%s\" {\n", mod.Type, mod.Name)

		// Write attributes
		for k, v := range mod.Attributes {
			fmt.Fprintf(f, "  %s = \"%s\"\n", k, v)
		}

		fmt.Fprintf(f, "}\n")
		f.Close()
	}

	return nil
}
